# Generated by Django 5.0.6 on 2024-05-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='dateofbirth',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='location',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dateofbirth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='location',
        ),
    ]
