# Generated by Django 5.0.6 on 2024-06-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0002_remove_faculty_contact_remove_faculty_dateofbirth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('product_count', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
