# Generated by Django 5.0.6 on 2024-06-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0003_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
