# Generated by Django 5.0.6 on 2024-06-24 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0004_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='department',
            name='enrollment_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='faculty',
            name='enrollment_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Core Courses', 'Core Courses'), ('Elective Courses', 'Elective Courses'), ('General Education Courses', 'General Education Courses'), ('Practicals and Labs', 'Practicals and Labs'), ('Seminar and Workshops', 'Seminar and Workshops')], max_length=100),
        ),
    ]
