# Generated by Django 5.0.6 on 2024-06-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0005_course_enrollment_date_department_enrollment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='department',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
    ]
